

package anis.com.beer.order.service.domain;

public enum BeerOrderStatusEnum {
    NEW, VALIDATED,VALIDATION_PENDING,VALIDATION_EXCEPTION,ALLOCATION_PENDING,ALLOCATED,ALLOCATION_EXCEPTION,
    PENDING_INVENTORY,DELIVERED,DELIVERED_EXCEPTION,READY, PICKED_UP,CANCELLED, DELIVERY_EXCEPTION;
}
