package anis.com.beer.order.service.domain;

public enum BeerOrderEventEnum {
    VALIDATE_ORDER, VALIDATION_PASSED,VALIDATION_FAILED,ALLOCATED_ORDER,
    ALLOCATION_SUCCESS,ALLOCATION_NO_INVENTORY,ALLOCATION_FAILED,
    CANCEL_ORDER,BEERORDER_PICKED_UP,ALLOCATE_ORDER;

}
